services:
  gh-mirror:
    build: .
    container_name: gh-nas-mirror
    user: root
    restart: unless-stopped
    environment:
      GITHUB_USERNAME: "${GITHUB_USERNAME}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      INTERVAL_MINUTES: "10"
      INCLUDE_FORKS: "false"
      EXCLUDE_ARCHIVED: "true"
    volumes:
      - /volume1/github-save/github-mirror:/volume1/github-save/github-mirror
    working_dir: /app
    command: python -u mirror.py



