version: "3.8"
services:
  gh-mirror:
    image: python:3.12-slim
    container_name: gh-nas-mirror
    user: "1000:10"   
    restart: unless-stopped
    environment:
      GITHUB_USERNAME: "${GITHUB_USERNAME}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      INTERVAL_MINUTES: "10"
      INCLUDE_FORKS: "false"
      EXCLUDE_ARCHIVED: "true"
    volumes:
      - /volume/github-save/github-mirror:/nas        # Change to your volume path if needed
      - /volume/github-save/github-cache:/data/cache  # Change to your volume path if needed
      - /volume/docker/github-nas-mirror:/app:ro      # Change to your volume path if needed
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python -u mirror.py"
